### ISSUE TITLE
Is this method available for all t2v models?

### ISSUE THREAD

**Issue by AdvancedHe** [wuyushuwys/FMEDiffusion#1]
Hi, guys, thanks for your great work!
As shown in title, I want to ask if this work available for others t2v models? If yes, I want to ask how to use in other model?
Thanks a lot!

**Comment by wuyushuwys** [comment]
Hello @AdvancedHe , our method works on most spatial-temporal models but not for models with 3D operators.

**Comment by AdvancedHe** [comment]
Hi @wuyushuwys 
I'd like to know, according to this script:
```
import torch
from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_gif
# import our module wrapper
from fme import FMEWrapper

# load pipeline
pipe = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid", torch_dtype=torch.float16, variant="fp16"
)
pipe.to('cuda')

# initialize wrapper
helper = FMEWrapper(num_temporal_chunk=7, num_spatial_chunk=7, num_frames=pipe.unet.config.num_frames)
# wrap pipeline
helper.wrap(pipe)

# Inference as normal
image = load_image(
    "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
# no decode_chunk_size required!
frames = pipe(image, generator=generator).frames[0]

export_to_gif(frames, "generated_fme.gif", fps=7)
```
If my model meets the requirements, do I only need to change the pipeline to my own, without making any other changes?
Looking forward your answer.
Thanks a lot.

**Comment by wuyushuwys** [comment]
Hello @AdvancedHe, additional modifications will be required. The current wrapper only supports stable video diffusion.
We plan to support models with updated wrappers in the future. You can also implement them by following the paper.

**Comment by AdvancedHe** [comment]
> Hello @AdvancedHe, additional modifications will be required. The current wrapper only supports stable video diffusion. We plan to support models with updated wrappers in the future. You can also implement them by following the paper.

Ok. thanks for your reply.
I will implement them following the paper. By the way, could you tell me when will you update the support ?

**Comment by wuyushuwys** [comment]
We've added support for AnimateDiff in the latest update.
