### ISSUE TITLE
About Operator Grouping

### ISSUE THREAD

**Issue by darui18** [wuyushuwys/FMEDiffusion#3]
Hi, guys, thanks for your great work!
I'm not familiar with the code, I want to konw where is the code related to Operator Grouping? 
Thanks a lot!

**Comment by wuyushuwys** [comment]
Hello, you can refer to [here](https://github.com/wuyushuwys/FMEDiffusion/blob/main/src/fme/nn/blocks.py#L80). This part contains the simulation for operator grouping.
